name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
        
    - name: Build
      run: npm run build
      env:
        VITE_GEMINI_API_KEY: ${{ secrets.VITE_GEMINI_API_KEY }}
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        VITE_N8N_BASE_URL: ${{ secrets.VITE_N8N_BASE_URL }}
        VITE_N8N_WEBHOOK_URL: ${{ secrets.VITE_N8N_WEBHOOK_URL }}
        VITE_N8N_API_KEY: ${{ secrets.VITE_N8N_API_KEY }}
        VITE_UPTIME_ROBOT_API_KEY: ${{ secrets.VITE_UPTIME_ROBOT_API_KEY }}
        VITE_UPTIME_ROBOT_READONLY_API_KEY: ${{ secrets.VITE_UPTIME_ROBOT_READONLY_API_KEY }}
        VITE_UPTIME_ROBOT_BASE_URL: ${{ secrets.VITE_UPTIME_ROBOT_BASE_URL }}
        VITE_AI_MODEL: ${{ secrets.VITE_AI_MODEL }}
        VITE_AI_MAX_TOKENS: ${{ secrets.VITE_AI_MAX_TOKENS }}
        VITE_AI_TEMPERATURE: ${{ secrets.VITE_AI_TEMPERATURE }}
        VITE_APP_NAME: ${{ secrets.VITE_APP_NAME }}
        VITE_APP_VERSION: ${{ secrets.VITE_APP_VERSION }}
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
